# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReplacePathBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata: str=None, file: str=None):  # noqa: E501
        """ReplacePathBody - a model defined in Swagger

        :param metadata: The metadata of this ReplacePathBody.  # noqa: E501
        :type metadata: str
        :param file: The file of this ReplacePathBody.  # noqa: E501
        :type file: str
        """
        self.swagger_types = {
            'metadata': str,
            'file': str
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'file': 'file'
        }
        self._metadata = metadata
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'ReplacePathBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The replace_path_body of this ReplacePathBody.  # noqa: E501
        :rtype: ReplacePathBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> str:
        """Gets the metadata of this ReplacePathBody.


        :return: The metadata of this ReplacePathBody.
        :rtype: str
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: str):
        """Sets the metadata of this ReplacePathBody.


        :param metadata: The metadata of this ReplacePathBody.
        :type metadata: str
        """

        self._metadata = metadata

    @property
    def file(self) -> str:
        """Gets the file of this ReplacePathBody.


        :return: The file of this ReplacePathBody.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this ReplacePathBody.


        :param file: The file of this ReplacePathBody.
        :type file: str
        """

        self._file = file
