# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdatePathBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata: object=None):  # noqa: E501
        """UpdatePathBody - a model defined in Swagger

        :param metadata: The metadata of this UpdatePathBody.  # noqa: E501
        :type metadata: object
        """
        self.swagger_types = {
            'metadata': object
        }

        self.attribute_map = {
            'metadata': 'metadata'
        }
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'UpdatePathBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The update_path_body of this UpdatePathBody.  # noqa: E501
        :rtype: UpdatePathBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> object:
        """Gets the metadata of this UpdatePathBody.


        :return: The metadata of this UpdatePathBody.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this UpdatePathBody.


        :param metadata: The metadata of this UpdatePathBody.
        :type metadata: object
        """

        self._metadata = metadata
