# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UpdatePathBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, file: str = None, json_data: str = None):  # noqa: E501
        """UpdatePathBody - a model defined in Swagger

        :param file: The file of this UpdatePathBody.  # noqa: E501
        :type file: str
        :param json_data: The json_data of this UpdatePathBody.  # noqa: E501
        :type json_data: str
        """
        self.swagger_types = {"file": str, "json_data": str}

        self.attribute_map = {"file": "file", "json_data": "json_data"}
        self._file = file
        self._json_data = json_data

    @classmethod
    def from_dict(cls, dikt) -> "UpdatePathBody":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The upload_body of this UpdatePathBody.  # noqa: E501
        :rtype: UpdatePathBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> str:
        """Gets the file of this UpdatePathBody.


        :return: The file of this UpdatePathBody.
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file: str):
        """Sets the file of this UpdatePathBody.


        :param file: The file of this UpdatePathBody.
        :type file: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file

    @property
    def json_data(self) -> str:
        """Gets the json_data of this UpdatePathBody.


        :return: The json_data of this UpdatePathBody.
        :rtype: str
        """
        return self._json_data

    @json_data.setter
    def json_data(self, json_data: str):
        """Sets the json_data of this UpdatePathBody.


        :param json_data: The json_data of this UpdatePathBody.
        :type json_data: str
        """
        if json_data is None:
            raise ValueError("Invalid value for `json_data`, must not be `None`")  # noqa: E501

        self._json_data = json_data


# class UpdatePathBody(Model):
#     """NOTE: This class is auto generated by the swagger code generator program.

#     Do not edit the class manually.
#     """
#     def __init__(self, file: str=None):  # noqa: E501
#         """UpdatePathBody - a model defined in Swagger

#         :param file: The file of this UpdatePathBody.  # noqa: E501
#         :type file: str
#         """
#         self.swagger_types = {
#             'file': str
#         }

#         self.attribute_map = {
#             'file': 'file'
#         }
#         self._file = file

#     @classmethod
#     def from_dict(cls, dikt) -> 'UpdatePathBody':
#         """Returns the dict as a model

#         :param dikt: A dict.
#         :type: dict
#         :return: The update_path_body of this UpdatePathBody.  # noqa: E501
#         :rtype: UpdatePathBody
#         """
#         return util.deserialize_model(dikt, cls)

#     @property
#     def file(self) -> str:
#         """Gets the file of this UpdatePathBody.


#         :return: The file of this UpdatePathBody.
#         :rtype: str
#         """
#         return self._file

#     @file.setter
#     def file(self, file: str):
#         """Sets the file of this UpdatePathBody.


#         :param file: The file of this UpdatePathBody.
#         :type file: str
#         """

#         self._file = file
